name: 'fork-sync-action'
description: 'Keep your fork up to date'
author: 'TG908'
inputs:
  owner:
    description: 'Owner of the forked repository'
    required: true
  github_token:
    description: 'Token for the github API'
    required: true
  origin_branch:
    description: 'Branch to track'
    required: false
    default: 'master'
  destination_branch:
    description: 'Branch to keep updated'
    required: false
    default: 'master'
  merge_method:
    description: 'Merge method to use'
    required: false
    default: 'rebase'

runs:
  using: 'node12'
  main: 'lib/main.js'
